version: "3.8"
services:
  hdi1:
    build: .
    container_name: hdi1-gen-runner
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    volumes:
      - ./hdi1-cache:/root/.cache/huggingface
      - ./outputs:/root/outputs/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: >
      bash -c "source /workspace/venv/bin/activate && python -m hdi1 -m dev -o /root/outputs/output.png 'A cat holding a sign that says Hello'"
